### PR TITLE
Add support for 448-bit integers and fields

### PR DESCRIPTION
**Pull request by daira**
## Description

Add support for 448-bit integers and fields. These will be needed for the Pluto and Eris curves
(https://github.com/daira/pluto-eris).

The changes are trivial and amount to applying the existing macros to a length of 448 bits (7 64-bit words).
This interacts with #186, but it should be easy to resolve any conflict.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (master)
- [x] ~~Linked to Github issue with discussion and accepted design~~ OR have an explanation in the PR that describes this work.
- [x] Wrote unit tests
- [ ] Updated relevant documentation in the code [not needed]
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Review by Pratyush — APPROVED** [review]
Thanks for the PR!

**Comment by daira** [comment]
Changing this to draft while I check that it actually works for Pluto/Eris (there seems to be some minor problem with `SquareRootField`, so perhaps I missed something).

**Comment by daira** [comment]
I didn't miss anything. When testing with the Pluto/Eris implementation I just needed to patch `ark-ff` and `ark-serialize` to use the 0.2.0 releases plus this patch only. I.e. in `Cargo.toml`:
```
[patch.crates-io]
ark-ff = { path = '../algebra/ff' }
ark-serialize = { path = '../algebra/serialize' }
```
And then it works. So, I think this PR is fine. (I rebased it relative to the 0.2.0 release for more straightforward testing.)

**Review by ValarDragon — APPROVED** [review]
LGTM!

**Pull request merged**
