### PR TITLE
Fix a corner case for ate pairing in BLS12 and BW6 models

### PR DESCRIPTION
**Pull request by weikengchen**
## Description

This PR changes the BLS12 and BW6 model's treatment of the ate pairing count. Otherwise, for certain input, it may fail.

closes: #459 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (master)
- [x] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Wrote unit tests
- [x] Updated relevant documentation in the code
- [x] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the GitHub PR explorer

### CODE REVIEW

**Comment by weikengchen** [comment]
Reference: introducing two CP curves that embed curve25519. Thanks @Pratyush particularly for pointing out the importance of having D = -3 and providing more information about conditions for a sextic twist.
https://github.com/DZK-Labs/ark-yafa/

**Comment by weikengchen** [comment]
Note: this PR needs to be redone after #447. Since it would introduce a conflict to #447, it should not be merged.

**Review by Pratyush — APPROVED** [review]

**Comment by Pratyush** [comment]
It's fine to merge this; there should not be any conflict with master.

**Comment by codeblooded1729** [comment]
We also need to fix it in `g2.rs` files for both models. More specifically, you need to do the same edit in the loop where ell coefficients are generated.

**Comment by Pratyush** [comment]
Thanks for flagging this @codeblooded1729 ; @weikengchen can you handle that?

**Comment by weikengchen** [comment]
Yes---I would need to do a pass. But if I remember correctly, this does not affect those two files as their ate loop counts are not hitting this corner case.

**Pull request merged**
