### PR TITLE
Curves: start homogeneizing cargo toml

### PR DESCRIPTION
**Pull request by dannywillems**
## Description

Using cargo workspace. It helps sharing all the dependencies.
This is unfinished. Let me know if you agree with the changes and I will continue.

closes: N/A

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (master)
- [x] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] N/A Wrote unit tests
- [ ] N/A Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the GitHub PR explorer

### CODE REVIEW

**Comment by mmagician** [comment]
This is great!

**Comment by Pratyush** [comment]
Apologies for the delay in reviewing; this looks like a great change. Please go ahead and complete the changes.

**Comment by Pratyush** [comment]
I think this is fixed @mmagician ?

**Comment by dannywillems** [comment]
LGTM! Thanks. Sorry if I didn't have time to finish.

**Pull request closed without merging**
