### PR TITLE
Switch comments for unchecked and checked msm versions

### PR DESCRIPTION
**Pull request by kevaundray**
## Description

closes: #319

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (master)
- [ ] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests
- [ ] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer

### CODE REVIEW

**Comment by weikengchen** [comment]
Is it true that `msm_unchecked` should actually be `msm_checked`?

**Comment by kevaundray** [comment]
I am not sure what the default behaviour of `msm` is intended to be here, I only changed the comments to match what the implementation is doing.

It looks like the intended default behaviour is: 

- `msm` should truncate, ie it's basically `msm_unchecked`
- `msm_unchecked` is actually checking the arguments and should be `msm_checked`

I'm having problems with my laptop at the moment, so feel free to make any changes you see fit

**Comment by mmaker** [comment]
On Sun 20 Nov 2022 at 17:02, kevaundray ***@***.***> wrote:

> I am not sure what the default behaviour of msm is intended to be here, I
> only changed the comments to match what the implementation is doing.
>
> It looks like the intended default behaviour is:
>
>    - msm should truncate, ie it's basically msm_unchecked
>    - msm_unchecked is actually checking the arguments and should be
>    msm_checked
>
> I'm having problems with my laptop at the moment, so feel free to make any
> changes you see fit
>

That’s correct, the reason being that in Rust unsafe is always more verbose

**Comment by Pratyush** [comment]
Yes, it should be the case that `msm` checks lengths, and `msm_unchecked` does not.

**Review by Pratyush — COMMENTED** [review]
This looks good to me. I believe you only need to fix some tests now that the type signatures are switched.

**Pull request merged**
