### PR TITLE
Add documentation to Field, PrimeField

### PR DESCRIPTION
**Pull request by horacepan**
## Description
This pull request adds documentation/simple code examples to the `Field` and `PrimeField` traits.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (master)
- [ ] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests
- [x] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer

### CODE REVIEW

**Comment by mmaker** [comment]
Running `cargo test --doc` we have several failures:

```
test src/fields/mod.rs - fields::Field (line 65) ... FAILED
test src/fields/mod.rs - fields::PrimeField (line 317) ... FAILED
```

Can you take care of them? There's `[dev-dependencies]` in the cargo toml file that will have to be edited.

**Comment by Pratyush** [comment]
Thanks! I'd appreciate it if you could attach screenshots showing what the new documentation looks like.

**Comment by horacepan** [comment]
@mmaker Ahh my bad, I tested in a repo outside of the package and assumed it'd be fine. Updated and the `cargo test --doc`  passes. I switched to using `use ark_test_curves::bls12_381::Fq as F;` to avoid any additions to `dev-dependencies` but lmk if I should instead stick with `use ark_test_curves::bls12_381::Fq as F;` and change the `dev-dependencies` accordingly.

@Pratyush here are some screenshots of the updated documentation:
image
image
image

**Comment by horacepan** [comment]
messed up the rebase, trying to fix now ...

**Comment by horacepan** [comment]
okay rebase fixed

**Comment by mmagician** [comment]
@horacepan `ark_test_curves` is recommended, and we already use it in doc examples under `ark-ff`.

**Comment by horacepan** [comment]
@mmaker @Pratyush so does this look alright to merge?

**Review by Pratyush — APPROVED** [review]

**Pull request merged**
