### PR TITLE
Fix prime order field sum of products test for k * 64 + 1 bits field

### PR DESCRIPTION
**Pull request by weikengchen**
## Description

This PR fixes the prime order field's sum of products test when the field modulus is k * 64 + 1 bits. 

The overflowing error is because the code tries to do ">> 64". We solve this issue by doing " = 0" when we need to shift 64 bits here.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (master)
- [x] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Re-reviewed `Files changed` in the GitHub PR explorer

N/A:
- [ ] Wrote unit tests
- [ ] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`

### CODE REVIEW

**Review by Pratyush — APPROVED** [review]

**Comment by Pratyush** [comment]
This should be to master, right?

**Comment by weikengchen** [comment]
So now we push fixes to master first and then send to release-0.4?

**Comment by weikengchen** [comment]
let me recreate the PR when I finish the debugging.

**Comment by Pratyush** [comment]
> So now we push fixes to master first and then send to release-0.4?

Yes, release-0.4 is only the branch from which we release

**Comment by weikengchen** [comment]
Close this PR in order to create a new one.

**Pull request closed without merging**
