### PR TITLE
Remove `ATE_LOOP_COUNT_IS_NEGATIVE` from BN curve parameter trait

### PR DESCRIPTION
**Pull request by weikengchen**
## Description

In #275, Daira pointed out that the current BN parameter trait, which requires `X_IS_NEGATIVE` and `ATE_LOOP_COUNT_IS_NEGATIVE`, can be improved.

Because for BN curves, the ate loop count is 6x+2, so `ATE_LOOP_COUNT_IS_NEGATIVE == X_IS_NEGATIVE` always hold.

Therefore, we may want to keep only one of them. It seems easier to remove `ATE_LOOP_COUNT_IS_NEGATIVE`. This PR makes this change.

To avoid breaking, this PR does not delete `ATE_LOOP_COUNT_IS_NEGATIVE` but adds a default implementation:

```
const ATE_LOOP_COUNT_IS_NEGATIVE: bool = Self::X_IS_NEGATIVE;
```

This is to avoid breaking `ark-curves`. Any thoughts? Should we remove it directly and add a pending PR for `ark-curves`? I will wait for people's opinions on this and then decide what changelog entry to add ("improvement" or "breaking").

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (master)
- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Updated relevant documentation in the code
- [x] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

N/A:
- [ ] Wrote unit tests

### CODE REVIEW

**Comment by Pratyush** [comment]
Let's remove it; I doubt anybody except `ark-curves` (and maybe `ark-r1cs-std`) is relying on this.

**Comment by weikengchen** [comment]
This PR is better merged right before the next release because merging this PR would cause all tests against curves to be "canceled" and may affect development. 

Added the `merge-in-next-release` label.

**Review by daira — APPROVED** [review]
Untested ACK

**Review by ValarDragon — APPROVED** [review]
LGTM

**Comment by weikengchen** [comment]
(Convert it into the draft to avoid accidental merging)

**Pull request merged**
