### PR TITLE
add Canonical(De-)Serialize to miller loop args

### PR DESCRIPTION
**Pull request by achimcc**
## Description

Adds `CanonicalSerialize` and `CanonicalDeserialize` traits to the arguments of `multi_miller_loop`. 

This originates from a discussion in https://github.com/arkworks-rs/algebra/issues/537 and is in some sense a follow-up of the PR's #534 and #542. It allows to avoid point preparation and instead to (de-)serialize the arguments of `multi_miller_loop` right away. It should finally be possible to over-come the forked models in https://github.com/paritytech/substrate/pull/13031 with this. 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (master)
- [x] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
~~- [ ] Wrote unit tests~~
- [x] Updated relevant documentation in the code
- [x] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the GitHub PR explorer
- [x]  Adopted unit tests

### CODE REVIEW

**Comment by achimcc** [comment]
Need to fix the tests first, will do later!

**Comment by burdges** [comment]
Why does this help?  Isn't it enough the specific model knows it can serialize its own G2Prepared?

**Comment by achimcc** [comment]
> Why does this help? Isn't it enough the specific model knows it can serialize its own G2Prepared?

But this is what @Pratyush suggested in https://github.com/arkworks-rs/algebra/issues/537#issuecomment-1368004136 ?

There is something wrong with the test curves / `test_pairing` macro. The test curve's affine points should implement `CanonicalSerialize` but the tests are throwing some errors...

**Comment by achimcc** [comment]
Changing `<$Pairing>::multi_pairing(&[a, c], &[b, d]);` -> `<$Pairing>::multi_pairing([a, c], [b, d]);` in the pairing testing macro in the test templates resolved the problem. I hope that's okay.

**Comment by achimcc** [comment]
After a detailed discussion we concluded that we still have to fork the models for usage in Substrate so that this PR is no longer a requirement for us.

**Pull request closed without merging**
