### PR TITLE
test mdlinter change

### PR DESCRIPTION
**Pull request by ValarDragon**
Looking into why mdlinter isn't working, making a PR just to get it to run

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (master)
- [ ] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests
- [ ] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by ValarDragon** [comment]
hrmm, looks like its working fine on master, maybe it only fails on PR's from outside the repo?

**Comment by weikengchen** [comment]
Yes. I previously fixed the linter failure by upgrading the linter docker image version (due to a bug related to GCC, #283). However, it is unable to handle #259 since it is in a different repo, and it seems that currently linter is unable to get that (linter pulls the master and then tries to switch the branch).

**Comment by ValarDragon** [comment]
Thanks for fixing that in 283!

I'm a bit confused why the correct branch doesn't get checked out, since the github actions checkout should handle going to the fork

**Comment by weikengchen** [comment]
A possibility, which I am totally unsure about, is whether the pull-request parameters are omittable? Since `ci.yml` does not have them.

https://github.com/arkworks-rs/algebra/blob/master/.github/workflows/mdlinter.yml#L10

(I am totally using heuristics here.)

**Comment by ValarDragon** [comment]
Lets try removing that, and see if it fixes anything

**Review by weikengchen — APPROVED** [review]

**Comment by weikengchen** [comment]
I have the feeling that we need to merge this in order to test. Merge?

**Comment by ValarDragon** [comment]
Yeah, lets merge this, and then check it on the next PR from outside the repo

**Comment by weikengchen** [comment]
Based on my rerunning of https://github.com/arkworks-rs/algebra/runs/2697545270, nope. 

I will we will revisit this issue when we have more ideas.

**Comment by weikengchen** [comment]
The current idea seems to be this: (1) before docker super-linter, the branch has been switched into an intermediate branch created by GitHub, like `pull/279/merge` (2) super-linter wants to build a list of files in master, and then sees which files have been changed.

https://github.com/github/super-linter/blob/3dc85fc3bc1f47c6cf14831c666f569b153e9fb9/lib/functions/buildFileList.sh#L67

And the failure seems to be right there.

One possibility: We can fix this by setting `VALIDATE_ALL_CODEBASE = true`.

**Comment by ValarDragon** [comment]
Thanks for tracing that, lets set that to true then

**Pull request merged**
