### PR TITLE
manual impl Hash on GroupProjective for consistency

### PR DESCRIPTION
**Pull request by alxiong**
## Description

closes: #299 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (master)
- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests
- [ ] ~Updated relevant documentation in the code~
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by alxiong** [comment]
@weikengchen Do you want me to add tests in `test-templates/src/curves.rs` for this?

**Review by weikengchen — APPROVED** [review]

**Comment by weikengchen** [comment]
I think additional tests, though can discover this issue, may not be needed, given that the change is quite predictable.

**Comment by weikengchen** [comment]
Thanks for the PR!

**Comment by burdges** [comment]
Rust need some facility for warnings when using specific trait impl.  I think even `HashMap: Clone` in std runs into "if you're using this then you maybe fucked up".  This is not as serious as that one, but it indicates a possible mistake.

**Comment by alxiong** [comment]
@burdges May I ask what's the context for this feedback? Are you suggesting we should do something different, revert back the changes or? (If so, would you help take a look at the original motivating case in #299 ?)

**Comment by burdges** [comment]
Nope.  No change.  :)  It's likely someone needs this, but also likely someone would use this when they should use `batch_normalize` first.  I've just noticed many cases like this where maybe clippy should advise against using the impl, but the impl itself is necessary.

**Pull request merged**
