### PR TITLE
CI jobs should run `cargo fmt` with nightly Rust

### PR DESCRIPTION
**Pull request by mmagician**
## Description

Otherwise we get warnings that most of the options in `rustfmt.toml` are ignored, see e.g. [the logs here](https://pipelinesghubeus23.actions.githubusercontent.com/Ja1ED82NlFonYCgxsb9MEIoY4GYjUCcm7KE16yZk5O90uqgHmi/_apis/pipelines/1/runs/4270/signedlogcontent/11?urlExpires=2024-02-07T09%3A20%3A23.3134822Z&urlSigningMethod=HMACV1&urlSignature=xO2I67K%2F48neave0oU9OBbP84kgElFhG5Y4i%2BX8TfJU%3D).

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (master)
- [ ] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests
- [ ] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer

### CODE REVIEW

**Comment by Pratyush** [comment]
I purposely *don't* run formatting with nightly because the average person runs stable, and it would be quite annoying if they format locally with stable, reformat the whole codebase, and then get confused. If needed we can comment out the nightly-only lines in `rustfmt.toml` to silence the errors

**Comment by mmagician** [comment]
From [`rustfmt` ](https://github.com/rust-lang/rustfmt?tab=readme-ov-file#limitations):
>  in particular, post-1.0, the formatting of most code should not change as Rustfmt improves.

I might be wrong, but the differences that nightly applies are to parts of the code that stable `fmt` doesn't yet format (i.e. the nightly-only rules specified in `rustfmt.toml`). Even if something changes in nightly, a subsequent run with `stable` shouldn't reformat anything.

Otherwise what you propose works, too.

**Comment by Pratyush** [comment]
Sure, but what I had in mind was the reverse: you write something, format it according to `cargo fmt` (i.e. stable), and then CI fails because it violated a nightly-only formatting rule. (This can happen, as evidenced by the diff for this PR)

**Comment by mmaker** [comment]
can we instead have a pull-request updated by an additional commit that automatically reformats the PR?

**Comment by mmagician** [comment]
@Pratyush Good point, I agree.

**Pull request closed without merging**
