### PR TITLE
cargo check failed when the rust version less than 1.49.0, add rust-t…

### PR DESCRIPTION
**Pull request by mengsuenyan**
cargo check failed when the rust version less than 1.49.0. may be can add rust-toolchain to specify the rust version;

when using the rust 1.48.0, the following error occurs:

```txt
    Checking zeroize v1.2.0
error[E0308]: mismatched types
   --> /home/lzj/.cargo/git/checkouts/algebra-7e23afa68841b66e/a3a1ab2/ff/src/fields/models/quadratic_extension.rs:272:24
    |
272 |             self.c0 *= v0;
    |                        ^^
    |                        |
    |                        expected reference, found associated type
    |                        help: consider borrowing here: `&v0`
    |
    = note:    expected reference `&<P as quadratic_extension::QuadExtParameters>::BaseField`
            found associated type `<P as quadratic_extension::QuadExtParameters>::BaseField`
    = help: consider constraining the associated type `<P as quadratic_extension::QuadExtParameters>::BaseField` to `&<P as quadratic_extension::QuadExtParameters>::BaseField`
    = note: for more information, visit https://doc.rust-lang.org/book/ch19-03-advanced-traits.html

error[E0308]: mismatched types
   --> /home/lzj/.cargo/git/checkouts/algebra-7e23afa68841b66e/a3a1ab2/ff/src/fields/models/quadratic_extension.rs:275:24
    |
275 |             self.c1 *= c0_copy;
    |                        ^^^^^^^
    |                        |
    |                        expected reference, found associated type
    |                        help: consider borrowing here: `&c0_copy`
    |
    = note:    expected reference `&<P as quadratic_extension::QuadExtParameters>::BaseField`
            found associated type `<P as quadratic_extension::QuadExtParameters>::BaseField`
    = help: consider constraining the associated type `<P as quadratic_extension::QuadExtParameters>::BaseField` to `&<P as quadratic_extension::QuadExtParameters>::BaseField`
    = note: for more information, visit https://doc.rust-lang.org/book/ch19-03-advanced-traits.html

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `ark-ff`

```

### CODE REVIEW

**Comment by jon-chuang** [comment]
This was a bug in stable rust, and I think only affects 1.48.

**Comment by Pratyush** [comment]
Thanks for the PR! I agree that this is valuable. Is the value specified in `rust-toolchain` respected when `algebra` crates are used as dependencies?

**Comment by ValarDragon** [comment]
This LGTM to merge

**Comment by huitseeker** [comment]
> Is the value specified in rust-toolchain respected when algebra crates are used as dependencies?

I'm afraid not. 

Besides, rust-toolchain files do not have the functionality of a MSRV, but rather work as a Rust version selector. We might be interested in a check such as the one in 
https://github.com/arkworks-rs/algebra/pull/255/commits/98b72589869923cb054a705127fdcd23bf69ecdf
instead.

**Comment by weikengchen** [comment]
Given that the main repo now requires 1.51, and this bug likely no longer applies to these newer versions of Rust, I closed this PR.

**Pull request closed without merging**
