### PR TITLE
added version of MNT4-753 Fq with small 2-adicity

### PR DESCRIPTION
**Pull request by npwardberkeley**
## Description

closes: #118 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (main)
- [ ] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests
- [ ] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by Pratyush** [comment]
Thanks for this! since this is just for testing, we can just make the small-adicity version the default (and remove the other one). We already test the high 2-adicity case via the BLS12 curve.

**Comment by weikengchen** [comment]
Looking at the current code, we may need to bump up the generator from 17 to 17 ^ {2^??}. I am looking into this.

**Comment by weikengchen** [comment]
Update: @Pratyush  we need some help.

Basically, it is hard to compute `T_MINUS_ONE_DIV_TWO` for our fake curve.

So, originally, T = (MODULUS - 1) / 2^S where S is the two-arity. Therefore, T is always an odd number.

But now, when we cheat that S = 3 (instead of S = 15), T is even, and T_MINUS_ONE_DIV_TWO is problematic.

-------

Is it possible for us to not modify T but still get the power down? Should we keep the T unchanged?

**Comment by weikengchen** [comment]
Close this PR, for two reasons:

1. It seems that we need to keep the current MNT-753 because in the `r1cs_std` we use it to test UInt64.
2. Likely what we are going to do---we add a new curve, probably BN384, since it is easier to find parameters---which would be used both for #118 and UInt64.
3. After the changes are done and are propagated to r1cs_std (and also the `succinct_r1cs` repo), we drop the MNT-753 curve from here.

**Comment by Pratyush** [comment]
Is the reason for using a pairing-friendly curve (BN384) just that it enables testing the Marlin gadget? If the curve doesn't need to be pairing friendly, you can just choose an arbitrary prime `p` that satisfies the smoothness requirements, and then generate a prime-order curve whose order is `p` via these tools: https://github.com/J08nY/ecgen or https://github.com/kwantam/eccons

**Comment by weikengchen** [comment]
Nope. Just appear that `ecfactory` has code that generates a curve for BN384.

(Currently debugging the generator, but should be done soon)

**Pull request closed without merging**
