### PR TITLE
Fix line function evaluation when adding for BLS12 G2

### PR DESCRIPTION
**Pull request by Pratyush**
## Description

Reported by user codeblooded in discord. Crosschecked against Eqn(13) in https://eprint.iacr.org/2013/722

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (master)
- [ ] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests
- [ ] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer

### CODE REVIEW

**Review by weikengchen — APPROVED** [review]

**Comment by weikengchen** [comment]
How breaking would this change be?

**Comment by simonmasson** [comment]
I think the code in `main` is actually right, and it is probably a typo on the paper you mentioned. See [this paper](https://eprint.iacr.org/2009/243.pdf) where it is indeed λ and not -λ. This explains why the tests do not pass with this modification. I am curious if this code was written following [this paper](https://eprint.iacr.org/2013/722) (with the typo) because it seems to be very similar (same names of variables, etc.), but without the typo :-) .

**Comment by weikengchen** [comment]
I think the best solution at this moment is to drop an email to the four authors.

**Comment by confuseSUN** [comment]
I agree that equation (13) is probably a typo, we can verify it with the tangent equation, in fact, for M types (j, -theta, lambda) and (-j, theta, -lambda) are equivalent.

**Comment by Pratyush** [comment]
Let's close this for the time being, seems like the paper was incorrect.

**Pull request closed without merging**
