### PR TITLE
Docs improvements

### PR DESCRIPTION
**Pull request by nnsW3**
Rectify typographical inaccuracies

This PR addresses several typographical errors across various files in the project. The changes improve readability and maintain the professional standard of the documentation and code comments.

Justification
Typographical errors, while minor, can detract from the overall quality of the project. Correcting these errors ensures clarity and professionalism, making the project more accessible and understandable for current and future contributors.

### CODE REVIEW

**Review by mmaker — APPROVED** [review]

**Comment by mmagician** [comment]
looks like commit farming if you ask me

**Comment by mmaker** [comment]
I know, but also i don't know if it's a good ground to reject the PR of a new user. Maybe we should squash these sort of PR ?

**Comment by nnsW3** [comment]
I am trying to contribute with typos, even if I am not yet able to make improvements to the code, I know it is not much but maybe it helps.

**Comment by mmagician** [comment]
@mmaker it's hard to say in general, I just wanna point out that these are not meaningful typos.

**Comment by nnsW3** [comment]
i have done my best is up to you, is hard to read all that docs, to be honest but your call sir

**Comment by weikengchen** [comment]
We do not encourage minor PRs for typos. I would close this PR.

**Pull request closed without merging**
