### PR TITLE
Switch to using RPITIT for `to_base_prime_field_elements`

### PR DESCRIPTION
**Pull request by Pratyush**
## Description

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (master)
- [ ] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests
- [ ] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer

### CODE REVIEW

**Comment by mmagician** [comment]
We're still at minimum supported `rust-version = "1.70"`, so we'd need to bump to 1.75 first, which would be pretty limiting to some projects.

**Comment by Pratyush** [comment]
We can hold off on this for a couple of release, just wanted to get this on the radar.

**Comment by Pratyush** [comment]
It's been a few releases, so maybe we can merge this now?

**Comment by mmagician** [comment]
@Pratyush sounds good, could you also bump the minimum `rust-version` together with this PR?

**Comment by Pratyush** [comment]
Done!

**Pull request merged**
