### PR TITLE
Move h2c tests to test-templates

### PR DESCRIPTION
**Pull request by mmagician**
## Description

Hashing to more curves is [WIP](https://github.com/arkworks-rs/curves/pull/138), and we should have a unified suite for checking against test vectors.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (master)
- [ ] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests
- [ ] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer

### CODE REVIEW

**Comment by Pratyush** [comment]
This is a great idea. Should we add the existing tests in this repo to test-curves, using the new macro?

**Comment by mmagician** [comment]
@Pratyush See the companion PR in curves: https://github.com/arkworks-rs/curves/pull/139.
We can of course still add them here, though, if you think that's better.

**Comment by Pratyush** [comment]
Let's add it in both, because the curves-algebra integration is often out of sync, so it's useful to get immediate feedback

**Comment by mmagician** [comment]
@Pratyush I've added them to test-curves too, and slighlty adapted the macro now so that we can specify the path where the test vectors are located. Ready for review!

**Review by Pratyush — APPROVED** [review]

**Pull request merged**
